version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: banco_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: NovaSenha@123
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    depends_on:
      - mysql
    working_dir: /app
    command: ["python", "script.py"]

volumes:
  mysql_data:
